# Generated by Django 5.2.6 on 2025-10-07 20:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment_api", "0002_alter_doctorprofile_available_time_slots_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
